// Generated by tools/build_pml_mod.py; edit main.template.js and worker_runtime.js.
import {
  MixinType,
  PolyMod,
} from "https://cdn.polymodloader.com/pml/PolyModLoader/0.6.2/PolyTypes.js";

/*
 * This function is serialized by PolyModLoader and inserted into the exact
 * PolyTrack 0.6.2 simulation-worker message handler. Keep every dependency in
 * the function body: imported bindings are not available in the worker blob.
 */
function polybotWorkerInjection() {
  {
    const runtimeKey = "__polybotWorkerRuntime_v2";

    if (!self[runtimeKey]) {
      self[runtimeKey] = (() => {
        const cars = e;
        const advanceCar = n;
        const messageTypes = Ki;
        const protocol = "polybot.sim";
        const protocolVersion = 2;
        const requestedBridgePort = Number(r.polybotBridgePort ?? 8765);
        const bridgePort = Number.isInteger(requestedBridgePort) &&
          requestedBridgePort > 0 && requestedBridgePort < 65536 ? requestedBridgePort : 8765;
        const bridgeUrl = "ws://127.0.0.1:" + bridgePort;
        const fixedDtSeconds = 0.001;
        const maxTicksPerStep = 250;
        const maxLookaheadCount = 64;
        const referenceSampleTicks = 20;
        const maxReferenceTicks = 600000;
        const hiddenCarId = 2147483000;
        const reconnectDelayMs = 1000;
        const readyWaitMs = 8000;
        const finishDisplayDelayMs = 500;
        const relayName = "polybot-ghost-relay-v1";

        let socket = null;
        let reconnectTimer = null;
        let internalDispatchDepth = 0;
        let activeRequestToken = null;
        let connectionGeneration = 0;
        let visualReplayRequestId = 0;
        let manualMode = false;
        let playerCarId = null;
        let lookaheadCount = null;
        let episodeCounter = 0;
        let session = null;
        let reference = null;
        let referenceRecording = null;
        let referenceTrackData = null;
        let gameVersion = "0.6.2";

        const createMessages = new Map();
        const startMessages = new Map();
        const localGhostMessages = new Map();
        const remoteGhostMessages = new Map();
        const visualReplayRequests = new Map();
        const workerRelayId = `${Date.now()}-${Math.random()}`;
        let ghostRelay = null;

        class BridgeError extends Error {
          constructor(code, message) {
            super(message);
            this.name = "BridgeError";
            this.code = code;
          }
        }

        function sendVisualReplayCommand(op, params) {
          const id = ++visualReplayRequestId;
          return new Promise((resolve, reject) => {
            const timer = setTimeout(() => {
              visualReplayRequests.delete(id);
              reject(new BridgeError("renderer_timeout", "main-thread replay renderer did not respond"));
            }, 30000);
            visualReplayRequests.set(id, { resolve, reject, timer });
            self.postMessage({ polybotVisualReplayCommand: { id, op, params } });
          });
        }

        function relayGhost(message) {
          try {
            ghostRelay?.postMessage({
              protocol: "polybot.ghost-relay",
              v: 1,
              source: workerRelayId,
              op: "ghost",
              message: {
                trackData: message.trackData,
                carRecording: message.carRecording,
              },
            });
          } catch (error) {
            console.warn("[PolyBot] Could not relay a ghost", error);
          }
        }

        if (typeof BroadcastChannel === "function") {
          try {
            ghostRelay = new BroadcastChannel(relayName);
            ghostRelay.addEventListener("message", (event) => {
              const data = event.data;
              if (
                !data ||
                data.protocol !== "polybot.ghost-relay" ||
                data.v !== 1 ||
                data.source === workerRelayId
              ) {
                return;
              }
              if (data.op === "request") {
                for (const message of localGhostMessages.values()) {
                  relayGhost(message);
                }
                return;
              }
              const message = data.message;
              if (
                data.op === "ghost" &&
                message &&
                typeof message.trackData === "string" &&
                message.carRecording != null
              ) {
                remoteGhostMessages.set(message.trackData, message);
              }
            });
            ghostRelay.postMessage({
              protocol: "polybot.ghost-relay",
              v: 1,
              source: workerRelayId,
              op: "request",
            });
          } catch (error) {
            ghostRelay = null;
            console.warn("[PolyBot] Ghost relay is unavailable", error);
          }
        }

        function finite(value, fallback = 0) {
          return Number.isFinite(value) ? value : fallback;
        }

        function clamp(value, minimum, maximum) {
          return Math.max(minimum, Math.min(maximum, value));
        }

        function add(a, b) {
          return [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
        }

        function subtract(a, b) {
          return [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
        }

        function scale(vector, amount) {
          return [vector[0] * amount, vector[1] * amount, vector[2] * amount];
        }

        function dot(a, b) {
          return a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
        }

        function cross(a, b) {
          return [
            a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0],
          ];
        }

        function length(vector) {
          return Math.sqrt(Math.max(0, dot(vector, vector)));
        }

        function distance(a, b) {
          return length(subtract(a, b));
        }

        function normalize(vector, fallback = [0, 0, 1]) {
          const magnitude = length(vector);
          if (!Number.isFinite(magnitude) || magnitude < 1e-8) {
            return [...fallback];
          }
          return scale(vector, 1 / magnitude);
        }

        function normalizeQuaternion(quaternion) {
          const magnitude = Math.sqrt(
            quaternion[0] * quaternion[0] +
              quaternion[1] * quaternion[1] +
              quaternion[2] * quaternion[2] +
              quaternion[3] * quaternion[3],
          );
          if (!Number.isFinite(magnitude) || magnitude < 1e-8) {
            return [0, 0, 0, 1];
          }
          return quaternion.map((value) => value / magnitude);
        }

        function quaternionMultiply(a, b) {
          return [
            a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1],
            a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0],
            a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3],
            a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2],
          ];
        }

        function quaternionDot(a, b) {
          return a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3];
        }

        function rotateVector(quaternion, vector) {
          const q = normalizeQuaternion(quaternion);
          const pure = [vector[0], vector[1], vector[2], 0];
          const conjugate = [-q[0], -q[1], -q[2], q[3]];
          const rotated = quaternionMultiply(quaternionMultiply(q, pure), conjugate);
          return [rotated[0], rotated[1], rotated[2]];
        }

        function requireObject(value, name) {
          if (value === null || typeof value !== "object" || Array.isArray(value)) {
            throw new BridgeError("invalid_request", `${name} must be an object`);
          }
          return value;
        }

        function findCar(carId) {
          return cars.find((car) => car.id === carId) ?? null;
        }

        function internalDispatch(message) {
          internalDispatchDepth += 1;
          try {
            self.onmessage({ data: message });
          } finally {
            internalDispatchDepth -= 1;
          }
        }

        function deleteAllCars() {
          const ids = cars.map((car) => car.id);
          for (const carId of ids) {
            internalDispatch({ messageType: messageTypes.DeleteCar, carId });
          }
        }

        function restoreCachedCars({ paused }) {
          deleteAllCars();
          for (const message of createMessages.values()) {
            internalDispatch(message);
          }
          for (const message of startMessages.values()) {
            if (createMessages.has(message.carId)) {
              internalDispatch(message);
            }
          }
          for (const car of cars) {
            car.isPaused = paused;
          }
        }

        function pauseManualCars() {
          if (!manualMode) {
            return;
          }
          for (const car of cars) {
            car.isPaused = true;
          }
        }

        function leaveManualMode() {
          if (!manualMode) {
            return;
          }
          manualMode = false;
          session = null;
          try {
            // Recreate at the start before returning control. This prevents a
            // native finished state, hidden from the UI, surfacing on the next
            // vanilla realtime tick.
            restoreCachedCars({ paused: false });
          } catch (error) {
            console.error("[PolyBot] Could not restore vanilla simulation", error);
            for (const car of cars) {
              car.isPaused = false;
            }
          }
        }

        function decodeState(buffer) {
          const bytes = new Uint8Array(buffer);
          if (bytes.byteLength < 84) {
            throw new BridgeError("invalid_state", "PolyTrack returned a short car-state packet");
          }
          const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
          let offset = 4;

          const frames = bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16);
          offset += 3;
          const speedKmh = view.getFloat32(offset, true);
          offset += 4;
          const flags = bytes[offset];
          offset += 1;
          const hasStarted = Boolean(flags & 1);
          const hasFinished = Boolean(flags & 2);
          const hasCheckpointToRespawnAt = Boolean(flags & 4);
          const contactFlags = [8, 16, 32, 64].map((mask) => Boolean(flags & mask));

          let finishFrames = null;
          if (hasFinished) {
            finishFrames =
              bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16);
            offset += 3;
          }

          const nextCheckpointIndex = view.getUint16(offset, true);
          offset += 2;
          const position = [
            view.getFloat32(offset, true),
            view.getFloat32(offset + 4, true),
            view.getFloat32(offset + 8, true),
          ];
          offset += 12;
          const quaternion = normalizeQuaternion([
            view.getFloat32(offset, true),
            view.getFloat32(offset + 4, true),
            view.getFloat32(offset + 8, true),
            view.getFloat32(offset + 12, true),
          ]);
          offset += 16;

          const impulseCount = view.getUint8(offset);
          offset += 1;
          if (impulseCount > 4) {
            throw new BridgeError("invalid_state", "PolyTrack returned too many collision impulses");
          }
          const collisionImpulses = [];
          for (let index = 0; index < impulseCount; index += 1) {
            collisionImpulses.push(view.getFloat32(offset, true));
            offset += 4;
          }

          for (const hasContact of contactFlags) {
            if (hasContact) {
              offset += 24;
            }
          }
          const wheelValues = [];
          for (let field = 0; field < 4; field += 1) {
            const values = [];
            for (let wheel = 0; wheel < 4; wheel += 1) {
              values.push(finite(view.getFloat32(offset, true)));
              offset += 4;
            }
            wheelValues.push(values);
          }
          const [suspensionLengths, suspensionVelocities, wheelRotations, wheelSkids] = wheelValues;
          const steering = view.getFloat32(offset, true);
          offset += 4;
          const controlFlags = view.getUint8(offset);

          if (offset >= bytes.byteLength) {
            throw new BridgeError("invalid_state", "PolyTrack car-state packet is truncated");
          }

          return {
            frames,
            speedKmh: finite(speedKmh),
            hasStarted,
            hasFinished,
            finishFrames,
            hasCheckpointToRespawnAt,
            nextCheckpointIndex,
            position: position.map((value) => finite(value)),
            quaternion,
            collisionImpulses: collisionImpulses.map((value) => finite(value)),
            wheelContacts: contactFlags,
            suspensionLengths,
            suspensionVelocities,
            wheelRotations,
            wheelSkids,
            steering: finite(steering),
            controls: {
              up: Boolean(controlFlags & 1),
              right: Boolean(controlFlags & 2),
              down: Boolean(controlFlags & 4),
              left: Boolean(controlFlags & 8),
              reset: Boolean(controlFlags & 16),
            },
          };
        }

        function addReferencePoint(points, decoded, controls, force = false) {
          const point = {
            frame: decoded.frames,
            expertAction: {
              steer: controls.right ? 1 : controls.left ? -1 : 0,
              throttle: controls.up ? 1 : 0,
              brake: controls.down ? 1 : 0,
            },
            position: decoded.position,
            quaternion: decoded.quaternion,
            nextCheckpointIndex: decoded.nextCheckpointIndex,
            s: 0,
            tangent: [0, 0, 1],
            up: [0, 1, 0],
            right: [1, 0, 0],
            curvature: 0,
          };
          const previous = points.at(-1);
          if (!previous) {
            points.push(point);
            return;
          }
          const separation = distance(previous.position, point.position);
          if (force || separation >= 0.15) {
            point.s = previous.s + separation;
            points.push(point);
          }
        }

        function finishReference(points) {
          if (points.length < 10) {
            throw new BridgeError(
              "missing_reference",
              "The loaded ghost did not produce a usable trajectory.",
            );
          }

          let forwardAgreement = 0;
          for (let index = 0; index < points.length; index += 1) {
            const previous = points[Math.max(0, index - 1)];
            const next = points[Math.min(points.length - 1, index + 1)];
            const tangent = normalize(subtract(next.position, previous.position));
            const up = normalize(rotateVector(points[index].quaternion, [0, 1, 0]), [0, 1, 0]);
            points[index].tangent = tangent;
            points[index].up = up;
            points[index].right = normalize(
              rotateVector(points[index].quaternion, [1, 0, 0]),
              [1, 0, 0],
            );
            forwardAgreement += dot(
              rotateVector(points[index].quaternion, [0, 0, 1]),
              tangent,
            );
          }

          const forwardSign = forwardAgreement >= 0 ? 1 : -1;

          for (let index = 1; index < points.length - 1; index += 1) {
            const before = points[index - 1];
            const after = points[index + 1];
            const angle = Math.atan2(
              dot(cross(before.tangent, after.tangent), points[index].up),
              clamp(dot(before.tangent, after.tangent), -1, 1),
            );
            const arc = Math.max(0.1, after.s - before.s);
            // Multiplying by forwardSign keeps positive curvature aligned with
            // the game's physical "right" control for either +Z- or
            // -Z-forward car assets.
            points[index].curvature = finite((angle * forwardSign) / arc);
          }
          points[0].curvature = points[1].curvature;
          points.at(-1).curvature = points.at(-2).curvature;

          return {
            points,
            length: points.at(-1).s,
            forwardSign,
          };
        }

        function buildReference(ghostCreateMessage) {
          internalDispatch({
            ...ghostCreateMessage,
            messageType: messageTypes.CreateCar,
            carId: hiddenCarId,
          });
          internalDispatch({
            messageType: messageTypes.StartCar,
            carId: hiddenCarId,
            targetSimulationTimeFrames: null,
          });

          const hiddenCar = findCar(hiddenCarId);
          if (!hiddenCar || hiddenCar.userControls !== null) {
            throw new BridgeError("missing_reference", "Could not initialize the loaded ghost lap.");
          }
          hiddenCar.isPaused = true;

          const points = [];
          let finished = false;
          try {
            for (let frame = 0; frame < maxReferenceTicks; frame += 1) {
              const controls = hiddenCar.controls.getControls(hiddenCar.frames);
              const buffer = advanceCar(hiddenCar, controls);
              hiddenCar.frames += 1;
              const decoded = decodeState(buffer);
              if (frame % referenceSampleTicks === 0 || decoded.hasFinished) {
                addReferencePoint(points, decoded, controls, decoded.hasFinished);
              }
              if (decoded.hasFinished) {
                finished = true;
                break;
              }
            }
          } finally {
            internalDispatch({ messageType: messageTypes.DeleteCar, carId: hiddenCarId });
          }

          if (!finished) {
            throw new BridgeError(
              "missing_reference",
              "The loaded ghost did not reach the finish within ten simulated minutes.",
            );
          }
          return finishReference(points);
        }

        function choosePlayerMessage() {
          if (playerCarId === null) {
            return null;
          }
          return createMessages.get(playerCarId) ?? null;
        }

        function chooseGhostMessage(playerMessage) {
          if (!playerMessage) {
            return null;
          }
          for (const message of createMessages.values()) {
            if (
              message.carRecording != null &&
              message.trackData === playerMessage.trackData
            ) {
              return message;
            }
          }
          return remoteGhostMessages.get(playerMessage.trackData) ?? null;
        }

        function readyForEpisode() {
          const playerMessage = choosePlayerMessage();
          return Boolean(playerMessage && chooseGhostMessage(playerMessage));
        }

        async function waitUntilReady() {
          const deadline = performance.now() + readyWaitMs;
          while (!readyForEpisode() && performance.now() < deadline) {
            await new Promise((resolve) => setTimeout(resolve, 50));
          }
          if (!choosePlayerMessage()) {
            throw new BridgeError(
              "game_not_ready",
              "Enter a PolyTrack time-trial race before starting PolyBot.",
            );
          }
          if (!chooseGhostMessage(choosePlayerMessage())) {
            throw new BridgeError(
              "missing_reference",
              "Load a ghost lap for the current track before starting PolyBot.",
            );
          }
        }

        function carBasis(decoded) {
          const sign = reference?.forwardSign ?? 1;
          const up = normalize(rotateVector(decoded.quaternion, [0, 1, 0]), [0, 1, 0]);
          const forward = normalize(
            rotateVector(decoded.quaternion, [0, 0, sign]),
            [0, 0, 1],
          );
          const right = normalize(
            rotateVector(decoded.quaternion, [1, 0, 0]),
            [1, 0, 0],
          );
          return { right, up, forward };
        }

        function findReferenceIndex(decoded) {
          const points = reference.points;
          const previousIndex = session?.referenceIndex ?? 0;
          const previousProgress = session?.progressM ?? 0;
          const displacement = session?.previousDecoded
            ? distance(decoded.position, session.previousDecoded.position)
            : 0;
          const firstProgress = Math.max(0, previousProgress - 2);
          const lastProgress = previousProgress + Math.max(12, displacement * 2 + 2);
          let first = previousIndex;
          while (first > 0 && points[first - 1].s >= firstProgress) {
            first -= 1;
          }
          let last = previousIndex;
          while (last + 1 < points.length && points[last + 1].s <= lastProgress) {
            last += 1;
          }
          let bestIndex = first;
          let bestDistanceSquared = Number.POSITIVE_INFINITY;
          for (let index = first; index <= last; index += 1) {
            if (points[index].nextCheckpointIndex !== decoded.nextCheckpointIndex) {
              continue;
            }
            const delta = subtract(decoded.position, points[index].position);
            const squared = dot(delta, delta);
            if (squared < bestDistanceSquared) {
              bestDistanceSquared = squared;
              bestIndex = index;
            }
          }
          // A checkpoint transition can briefly precede the next sampled ghost
          // point. Stay at the last guide point until that sample is in range.
          if (!Number.isFinite(bestDistanceSquared)) {
            bestIndex = previousIndex;
          }
          if (session) {
            session.referenceIndex = bestIndex;
            session.progressM = Math.max(session.progressM, points[bestIndex].s);
          }
          return bestIndex;
        }

        function findTimedReferencePoint() {
          const points = reference.points;
          const targetFrame = session.startReferenceFrame + session.tick;
          let index = session.timedReferenceIndex;
          while (
            index + 1 < points.length &&
            Math.abs(points[index + 1].frame - targetFrame) <=
              Math.abs(points[index].frame - targetFrame)
          ) {
            index += 1;
          }
          session.timedReferenceIndex = index;
          return points[index];
        }

        function angularVelocity(previousQuaternion, quaternion, dt, basis) {
          if (!previousQuaternion || dt <= 0) {
            return [0, 0, 0];
          }
          const previous = normalizeQuaternion(previousQuaternion);
          let delta = quaternionMultiply(quaternion, [
            -previous[0],
            -previous[1],
            -previous[2],
            previous[3],
          ]);
          if (delta[3] < 0) {
            delta = delta.map((value) => -value);
          }
          delta = normalizeQuaternion(delta);
          const halfSin = Math.sqrt(
            delta[0] * delta[0] + delta[1] * delta[1] + delta[2] * delta[2],
          );
          if (halfSin < 1e-8) {
            return [0, 0, 0];
          }
          const angle = 2 * Math.atan2(halfSin, clamp(delta[3], -1, 1));
          const world = scale([delta[0], delta[1], delta[2]], angle / (halfSin * dt));
          return [dot(world, basis.right), dot(world, basis.up), dot(world, basis.forward)].map(
            (value) => finite(value),
          );
        }

        function velocityBetween(previous, current, dtSeconds, basisOverride = null) {
          if (!previous || dtSeconds <= 0) {
            return [0, 0, 0];
          }
          const basis = basisOverride ?? carBasis(current);
          const worldVelocity = scale(
            subtract(current.position, previous.position),
            1 / dtSeconds,
          );
          return [
            dot(worldVelocity, basis.right),
            dot(worldVelocity, basis.up),
            dot(worldVelocity, basis.forward),
          ].map((value) => finite(value));
        }

        function buildTelemetry(decoded, action, dtSeconds) {
          const basis = carBasis(decoded);
          const referenceIndex = findReferenceIndex(decoded);
          const guide = reference.points[referenceIndex];
          // All ghost guidance must describe the nearest point on the racing
          // line. A time-indexed ghost can be hundreds of metres ahead after
          // the learner loses time, producing unrelated controls and poses.
          const timedGuide = guide;
          const offset = subtract(decoded.position, guide.position);
          const lateralOffset = dot(offset, guide.right);
          const headingError =
            (reference.forwardSign ?? 1) *
            Math.atan2(
              dot(cross(guide.tangent, basis.forward), basis.up),
              clamp(dot(guide.tangent, basis.forward), -1, 1),
            );

          const localVelocity = velocityBetween(
            session?.previousDecoded ?? null,
            decoded,
            dtSeconds,
          );
          const localAngularVelocity = angularVelocity(
            session?.previousDecoded?.quaternion ?? null,
            decoded.quaternion,
            dtSeconds,
            basis,
          );
          const localAcceleration = localVelocity.map((value, index) =>
            dtSeconds > 0 && session?.previousLocalVelocity
              ? finite((value - session.previousLocalVelocity[index]) / dtSeconds)
              : 0,
          );
          const ghostDelta = subtract(timedGuide.position, decoded.position);
          const ghostRelativePosition = [
            dot(ghostDelta, basis.right),
            dot(ghostDelta, basis.up),
            dot(ghostDelta, basis.forward),
          ].map((value) => finite(value));
          const ghostHeadingError = Math.atan2(
            dot(cross(basis.forward, timedGuide.tangent), basis.up),
            clamp(dot(basis.forward, timedGuide.tangent), -1, 1),
          );
          const timedIndex = referenceIndex;
          const speedBefore = reference.points[Math.max(0, timedIndex - 1)];
          const speedAfter = reference.points[Math.min(reference.points.length - 1, timedIndex + 1)];
          const speedFrames = Math.max(1, speedAfter.frame - speedBefore.frame);
          const ghostTargetSpeed =
            distance(speedBefore.position, speedAfter.position) / (speedFrames * fixedDtSeconds);

          const lookahead = [];
          const lookaheadMask = [];
          let cursor = referenceIndex;
          for (let index = 0; index < lookaheadCount; index += 1) {
            const targetDistance = guide.s + (index + 1) * 5;
            while (cursor < reference.points.length && reference.points[cursor].s < targetDistance) {
              cursor += 1;
            }
            if (cursor >= reference.points.length) {
              lookahead.push([0, 0, 0, 0]);
              lookaheadMask.push(0);
              continue;
            }
            const target = reference.points[cursor];
            const delta = subtract(target.position, decoded.position);
            lookahead.push([
              finite(dot(delta, basis.forward)),
              finite(dot(delta, basis.right)),
              finite(dot(delta, basis.up)),
              finite(target.curvature),
            ]);
            lookaheadMask.push(1);
          }

          const worldUp = [0, 1, 0];
          const pitch = Math.asin(clamp(basis.forward[1], -1, 1));
          const roll = Math.atan2(dot(basis.right, worldUp), dot(basis.up, worldUp));

          return {
            position_m: decoded.position.map((value) => finite(value)),
            quaternion_xyzw: decoded.quaternion.map((value) => finite(value)),
            local_velocity_mps: localVelocity,
            local_acceleration_mps2: localAcceleration,
            angular_velocity_radps: localAngularVelocity,
            up_vector: basis.up.map((value) => finite(value)),
            pitch_rad: finite(pitch),
            roll_rad: finite(roll),
            wheel_contacts: decoded.wheelContacts.map((contact) => (contact ? 1 : 0)),
            suspension_lengths_m: decoded.suspensionLengths,
            suspension_velocities_mps: decoded.suspensionVelocities,
            wheel_skids: decoded.wheelSkids,
            actual_steering: decoded.steering,
            ghost_relative_position_m: ghostRelativePosition,
            ghost_heading_error_rad: finite(ghostHeadingError),
            ghost_target_speed_mps: finite(ghostTargetSpeed),
            expert_action: guide.expertAction,
            checkpoint_index: decoded.nextCheckpointIndex,
            elapsed_s: session.tick * fixedDtSeconds,
            previous_action: action,
            track: {
              progress_m: finite(session?.progressM ?? guide.s),
              length_m: Math.max(0.1, finite(reference.length, 0.1)),
              half_width_m: 5,
              lateral_offset_m: finite(lateralOffset),
              heading_error_rad: finite(headingError),
              lookahead,
              lookahead_mask: lookaheadMask,
            },
          };
        }

        function publishStates(buffers, playerFinished = false) {
          const visibleBuffers = buffers.map((buffer) => buffer.slice(0));
          postMessage(
            {
              messageType: messageTypes.UpdateResult,
              carStateBuffers: visibleBuffers,
              polybotPlayerFinished: playerFinished,
            },
            { transfer: visibleBuffers },
          );
        }

        function transition(
          decoded,
          action,
          ticksAdvanced,
          events,
          seed = null,
          collisionImpulsePeak = null,
          kinematicDtSeconds = null,
        ) {
          const state = buildTelemetry(
            decoded,
            action,
            kinematicDtSeconds ?? ticksAdvanced * fixedDtSeconds,
          );
          const guide = reference.points[session.referenceIndex];
          const timedGuide = guide;
          const offTrack = Math.abs(state.track.lateral_offset_m) > state.track.half_width_m * 1.5;
          if (offTrack && !events.includes("off_track")) {
            events.push("off_track");
          }
          const result = {
            episode_id: session.episodeId,
            tick: session.tick,
            ticks_advanced: ticksAdvanced,
            state,
            events,
            info: {
              track_id: "current",
              guide: "loaded_ghost",
              reference_points: reference.points.length,
              guide_progress_m: finite(session.progressM),
              native_frame: decoded.frames,
              speed_kmh: decoded.speedKmh,
              collision_impulses:
                collisionImpulsePeak === null
                  ? decoded.collisionImpulses
                  : [finite(collisionImpulsePeak)],
              expert_action: guide.expertAction,
              ghost_position_error_m: finite(
                distance(decoded.position, timedGuide.position),
              ),
              ghost_rotation_error_rad: finite(
                2 *
                  Math.acos(
                    clamp(
                      Math.abs(
                        quaternionDot(
                          normalizeQuaternion(decoded.quaternion),
                          normalizeQuaternion(timedGuide.quaternion),
                        ),
                      ),
                      0,
                      1,
                    ),
                  ),
              ),
              off_track: offTrack,
              leaderboard_submission_blocked: true,
            },
          };
          if (seed !== null) {
            result.info.seed = seed;
            result.info.seed_ignored = true;
          }
          session.previousDecoded = decoded;
          session.previousLocalVelocity = state.local_velocity_mps;
          session.previousAction = action;
          return result;
        }

        async function resetEpisode(params) {
          if (lookaheadCount === null) {
            throw new BridgeError("invalid_state", "hello must be called before reset");
          }
          if (!Number.isSafeInteger(params.seed) || params.seed < 0) {
            throw new BridgeError("invalid_request", "seed must be a non-negative integer");
          }
          if (
            session &&
            !session.previousDecoded?.hasFinished &&
            params.native_restart !== false
          ) {
            postMessage({
              messageType: messageTypes.UpdateResult,
              carStateBuffers: [],
              polybotAbortRestart: true,
            });
            // Yield once so the main thread can process native Backspace. An
            // aborted run does not need the finish-only display pause.
            await new Promise((resolve) => setTimeout(resolve, 0));
          }
          if (params.track_id !== "current") {
            throw new BridgeError(
              "track_mismatch",
              "The PolyTrack worker controls the loaded track; use --track current.",
            );
          }
          const startProgressRatio = params.start_progress_ratio ?? 0;
          const startTimeSeconds = params.start_time_s ?? null;
          if (
            typeof startProgressRatio !== "number" ||
            !Number.isFinite(startProgressRatio) ||
            startProgressRatio < 0 ||
            startProgressRatio >= 1
          ) {
            throw new BridgeError(
              "invalid_request",
              "start_progress_ratio must be a finite number in [0, 1).",
            );
          }
          if (
            startTimeSeconds !== null &&
            (typeof startTimeSeconds !== "number" ||
              !Number.isFinite(startTimeSeconds) ||
              startTimeSeconds < 0)
          ) {
            throw new BridgeError(
              "invalid_request",
              "start_time_s must be null or a non-negative finite number.",
            );
          }
          if (startTimeSeconds !== null && startProgressRatio > 0) {
            throw new BridgeError(
              "invalid_request",
              "start_time_s and start_progress_ratio cannot both select a start.",
            );
          }

          await waitUntilReady();
          const playerMessage = choosePlayerMessage();
          const ghostCandidate = chooseGhostMessage(playerMessage);
          // Only the serialized controls cross the worker boundary. Terrain
          // and track initialization come from this player worker's own
          // CreateCar payload.
          const ghostMessage = {
            ...playerMessage,
            carRecording: ghostCandidate.carRecording,
          };
          if (!startMessages.has(playerMessage.carId)) {
            // PolyTrack normally sends StartCar on the first human driving
            // input. Create the same native message so the AI can initiate a
            // stationary race without requiring a key press from the user.
            startMessages.set(playerMessage.carId, {
              messageType: messageTypes.StartCar,
              carId: playerMessage.carId,
              targetSimulationTimeFrames: null,
            });
          }
          manualMode = true;
          try {
            deleteAllCars();
            try {
              if (
                !reference ||
                referenceRecording !== ghostMessage.carRecording ||
                referenceTrackData !== ghostMessage.trackData
              ) {
                reference = buildReference(ghostMessage);
                referenceRecording = ghostMessage.carRecording;
                referenceTrackData = ghostMessage.trackData;
              }
            } finally {
              restoreCachedCars({ paused: true });
            }

            const player = findCar(playerCarId);
            if (!player) {
              throw new BridgeError("game_not_ready", "Could not recreate the player car");
            }
            player.isPaused = true;
            const neutralControls = {
              up: false,
              right: false,
              down: false,
              left: false,
              reset: false,
            };
            const initialBuffers = [];
            let initialBuffer = null;
            let previousPlayerBuffer = null;
            let earlierPlayerBuffer = null;
            let initialAction = { steer: 0, throttle: 0, brake: 0 };
            let startReferenceIndex = 0;
            if (startProgressRatio > 0 || startTimeSeconds !== null) {
              startReferenceIndex = reference.points.findIndex((point) =>
                startTimeSeconds !== null
                  ? point.frame * fixedDtSeconds >= startTimeSeconds
                  : point.s >= reference.length * startProgressRatio,
              );
              if (startReferenceIndex < 0) {
                startReferenceIndex = reference.points.length - 1;
              }
              const targetFrame = reference.points[startReferenceIndex].frame;
              internalDispatch({
                ...ghostMessage,
                messageType: messageTypes.CreateCar,
                carId: hiddenCarId,
              });
              internalDispatch({
                messageType: messageTypes.StartCar,
                carId: hiddenCarId,
                targetSimulationTimeFrames: null,
              });
              const replayCar = findCar(hiddenCarId);
              if (!replayCar || replayCar.userControls !== null) {
                throw new BridgeError(
                  "missing_reference",
                  "Could not create the curriculum replay car.",
                );
              }
              replayCar.isPaused = true;
              try {
                while (player.frames < targetFrame) {
                  const replayControls = replayCar.controls.getControls(replayCar.frames);
                  initialAction = {
                    steer: replayControls.right ? 1 : replayControls.left ? -1 : 0,
                    throttle: replayControls.up ? 1 : 0,
                    brake: replayControls.down ? 1 : 0,
                  };
                  for (const car of cars) {
                    if (!car.hasStarted) {
                      continue;
                    }
                    const controls =
                      car.id === playerCarId || car.id === hiddenCarId
                        ? replayControls
                        : car.userControls === null
                          ? car.controls.getControls(car.frames)
                          : neutralControls;
                    const buffer = advanceCar(car, controls);
                    car.frames += 1;
                    if (car.id !== hiddenCarId) {
                      initialBuffers.push(buffer);
                      // Publish the curriculum prefix in bounded batches so
                      // native recording includes its exact input history.
                      if (initialBuffers.length >= maxTicksPerStep) {
                        publishStates(initialBuffers);
                        initialBuffers.length = 0;
                      }
                    }
                    if (car.id === playerCarId) {
                      earlierPlayerBuffer = previousPlayerBuffer;
                      previousPlayerBuffer = initialBuffer;
                      initialBuffer = buffer;
                    }
                  }
                }
              } finally {
                internalDispatch({ messageType: messageTypes.DeleteCar, carId: hiddenCarId });
              }
            } else {
              for (const car of cars) {
                if (!car.hasStarted) {
                  continue;
                }
                const controls =
                  car.id === playerCarId
                    ? neutralControls
                    : car.userControls === null
                      ? car.controls.getControls(car.frames)
                      : neutralControls;
                const buffer = advanceCar(car, controls);
                car.frames += 1;
                initialBuffers.push(buffer);
                if (car.id === playerCarId) {
                  initialBuffer = buffer;
                }
              }
            }
            if (!initialBuffer) {
              throw new BridgeError("game_not_ready", "The player car has not started");
            }
            const decoded = decodeState(initialBuffer);
            const previousDecoded = previousPlayerBuffer
              ? decodeState(previousPlayerBuffer)
              : decoded;
            const earlierDecoded = earlierPlayerBuffer
              ? decodeState(earlierPlayerBuffer)
              : previousDecoded;
            const historicalVelocity = velocityBetween(
              earlierDecoded,
              previousDecoded,
              fixedDtSeconds,
              carBasis(decoded),
            );
            publishStates(initialBuffers);

            episodeCounter += 1;
            session = {
              episodeId: `polytrack-${episodeCounter}`,
              tick: 0,
              previousDecoded,
              previousLocalVelocity: historicalVelocity,
              previousAction: initialAction,
              previousCheckpoint: decoded.nextCheckpointIndex,
              referenceIndex: startReferenceIndex,
              progressM: reference.points[startReferenceIndex].s,
              startReferenceFrame: reference.points[startReferenceIndex].frame,
              timedReferenceIndex: startReferenceIndex,
            };
            return transition(
              decoded,
              initialAction,
              0,
              [],
              params.seed,
              null,
              previousPlayerBuffer ? fixedDtSeconds : 0,
            );
          } catch (error) {
            leaveManualMode();
            throw error;
          }
        }

        function validateAction(value) {
          const action = requireObject(value, "action");
          if (![-1, 0, 1].includes(action.steer)) {
            throw new BridgeError("invalid_action", "steer must be -1, 0, or 1");
          }
          if (![0, 1].includes(action.throttle) || ![0, 1].includes(action.brake)) {
            throw new BridgeError("invalid_action", "throttle and brake must be 0 or 1");
          }
          return {
            steer: action.steer,
            throttle: action.throttle,
            brake: action.brake,
          };
        }

        async function stepEpisode(params) {
          if (!session || params.episode_id !== session.episodeId) {
            throw new BridgeError("stale_episode", "episode_id is stale or unknown");
          }
          if (
            !Number.isSafeInteger(params.ticks) ||
            params.ticks < 1 ||
            params.ticks > maxTicksPerStep
          ) {
            throw new BridgeError(
              "invalid_action",
              `ticks must be an integer from 1 to ${maxTicksPerStep}`,
            );
          }
          let actions;
          if (params.actions === undefined) {
            const action = validateAction(params.action);
            actions = Array.from({ length: params.ticks }, () => action);
          } else {
            if (!Array.isArray(params.actions) || params.actions.length !== params.ticks) {
              throw new BridgeError(
                "invalid_action",
                "actions must contain exactly one digital action per requested tick",
              );
            }
            actions = params.actions.map((action) => validateAction(action));
          }
          const player = findCar(playerCarId);
          if (!player) {
            throw new BridgeError("game_not_ready", "The player car no longer exists");
          }
          player.isPaused = true;
          let decoded = session.previousDecoded;
          // Native recording reads controls from every state and records them
          // at the previous state's frame. Skipping ticks loses PWM transitions
          // and shifts even constant controls to the wrong replay frame.
          const stateBuffers = [];
          let ticksAdvanced = 0;
          let collisionImpulsePeak = 0;
          for (let tick = 0; tick < params.ticks; tick += 1) {
            const tickAction = actions[tick];
            const controls = {
              up: Boolean(tickAction.throttle),
              right: tickAction.steer === 1,
              down: Boolean(tickAction.brake),
              left: tickAction.steer === -1,
              reset: false,
            };
            for (const car of cars) {
              if (!car.hasStarted) {
                continue;
              }
              const carControls =
                car.id === playerCarId
                  ? controls
                  : car.userControls === null
                    ? car.controls.getControls(car.frames)
                    : { up: false, right: false, down: false, left: false, reset: false };
              const buffer = advanceCar(car, carControls);
              car.frames += 1;
              stateBuffers.push(buffer);
              if (car.id === playerCarId) {
                decoded = decodeState(buffer);
                for (const impulse of decoded.collisionImpulses) {
                  collisionImpulsePeak = Math.max(collisionImpulsePeak, Math.abs(impulse));
                }
              }
            }
            ticksAdvanced += 1;
            if (decoded.hasFinished) {
              break;
            }
          }
          session.tick += ticksAdvanced;

          if (stateBuffers.length > 0) {
            publishStates(stateBuffers, decoded.hasFinished);
          }
          const events = [];
          if (decoded.nextCheckpointIndex > session.previousCheckpoint) {
            for (
              let index = session.previousCheckpoint;
              index < decoded.nextCheckpointIndex;
              index += 1
            ) {
              events.push("checkpoint");
            }
          }
          session.previousCheckpoint = decoded.nextCheckpointIndex;
          if (decoded.hasFinished) {
            events.push("finish");
          }
          const finalAction = actions[Math.max(0, ticksAdvanced - 1)];
          const result = transition(
            decoded,
            finalAction,
            ticksAdvanced,
            events,
            null,
            collisionImpulsePeak,
          );
          if (decoded.hasFinished) {
            // Let PolyTrack's native realtime loop animate the completed car
            // briefly instead of freezing the last fixed-step state onscreen.
            // Do not await this display pause: the successful step response must
            // reach Python before the main thread replaces the finished worker.
            for (const car of cars) {
              car.isPaused = false;
            }
            setTimeout(pauseManualCars, finishDisplayDelayMs + 100);
          }
          return result;
        }

        async function dispatchRequest(request, requestToken) {
          if (request.protocol !== protocol) {
            throw new BridgeError("unsupported_protocol", "unsupported protocol name");
          }
          if (request.v !== protocolVersion) {
            throw new BridgeError("unsupported_version", "unsupported protocol version");
          }
          if (!Number.isSafeInteger(request.id) || request.id < 0) {
            throw new BridgeError("invalid_request", "id must be a non-negative integer");
          }
          const params = requireObject(request.params, "params");
          switch (request.op) {
            case "hello":
              if (params.protocol !== protocol || params.protocol_version !== protocolVersion) {
                throw new BridgeError("unsupported_version", "trainer protocol is unsupported");
              }
              if (
                !Number.isSafeInteger(params.lookahead_count) ||
                params.lookahead_count < 1 ||
                params.lookahead_count > maxLookaheadCount
              ) {
                throw new BridgeError(
                  "invalid_request",
                  `lookahead_count must be from 1 to ${maxLookaheadCount}`,
                );
              }
              lookaheadCount = params.lookahead_count;
              return {
                protocol,
                protocol_version: protocolVersion,
                simulator: "polytrack-pml-worker",
                game_version: gameVersion,
                fixed_dt_s: fixedDtSeconds,
                max_ticks_per_step: maxTicksPerStep,
                lookahead_count: lookaheadCount,
                features: [
                  "local_finish_ui",
                  "fixed_step",
                  "native_physics",
                  "ghost_reference",
                  "cross_worker_reference",
                  "visible_car",
                  "action_sequence",
                  "visual_replay_swarm",
                ],
              };
            case "reset":
              return resetEpisode(params);
            case "step":
              return await stepEpisode(params);
            case "visual_replay_begin":
              return await sendVisualReplayCommand("begin", params);
            case "visual_replay_chunk":
              return await sendVisualReplayCommand("chunk", params);
            case "visual_replay_commit":
              return await sendVisualReplayCommand("commit", params);
            case "visual_replay_swarm_begin":
              return await sendVisualReplayCommand("swarm_begin", params);
            case "visual_replay_swarm_episode_begin":
              return await sendVisualReplayCommand("swarm_episode_begin", params);
            case "visual_replay_swarm_chunk":
              return await sendVisualReplayCommand("swarm_chunk", params);
            case "visual_replay_swarm_episode_commit":
              return await sendVisualReplayCommand("swarm_episode_commit", params);
            case "visual_replay_swarm_commit":
              return await sendVisualReplayCommand("swarm_commit", params);
            case "visual_replay_play":
            case "visual_replay_pause":
            case "visual_replay_restart":
            case "visual_replay_clear":
              return await sendVisualReplayCommand(request.op.slice("visual_replay_".length), params);
            case "visual_replay_seek":
              return await sendVisualReplayCommand("seek", params);
            case "visual_replay_speed":
            case "visual_replay_opacity":
            case "visual_replay_color":
            case "visual_replay_end_behavior":
            case "visual_replay_fade_duration":
            case "visual_replay_status":
              return await sendVisualReplayCommand(request.op.slice("visual_replay_".length), params);
            case "close":
              leaveManualMode();
              return { closed: true };
            default:
              throw new BridgeError(
                "unknown_operation",
                `unsupported operation: ${String(request.op)}`,
              );
          }
        }

        function send(targetSocket, message) {
          if (targetSocket?.readyState === WebSocket.OPEN) {
            targetSocket.send(JSON.stringify(message));
          }
        }

        async function onSocketMessage(sourceSocket, generation, raw) {
          let request = null;
          try {
            request = JSON.parse(raw);
            requireObject(request, "request");
          } catch (error) {
            send(sourceSocket, {
              protocol,
              v: protocolVersion,
              id: null,
              ok: false,
              error: { code: "malformed_json", message: error.message || String(error) },
            });
            return;
          }

          if (activeRequestToken !== null) {
            send(sourceSocket, {
              protocol,
              v: protocolVersion,
              id: request.id ?? null,
              ok: false,
              error: { code: "busy", message: "another simulator request is in progress" },
            });
            return;
          }

          const requestToken = { sourceSocket, generation };
          activeRequestToken = requestToken;
          try {
            const result = await dispatchRequest(request, requestToken);
            if (activeRequestToken !== requestToken) {
              return;
            }
            send(sourceSocket, { protocol, v: protocolVersion, id: request.id, ok: true, result });
            if (request.op === "close") {
              setTimeout(() => socket?.close(1000, "PolyBot bridge closed"), 0);
            }
          } catch (error) {
            const code = error instanceof BridgeError ? error.code : "adapter_error";
            console.error("[PolyBot] Request failed", error);
            send(sourceSocket, {
              protocol,
              v: protocolVersion,
              id: request.id ?? null,
              ok: false,
              error: { code, message: error.message || String(error) },
            });
          } finally {
            if (activeRequestToken === requestToken) {
              activeRequestToken = null;
            }
          }
        }

        function scheduleReconnect() {
          if (reconnectTimer !== null || playerCarId === null) {
            return;
          }
          reconnectTimer = setTimeout(() => {
            reconnectTimer = null;
            connectSocket();
          }, reconnectDelayMs);
        }

        function connectSocket() {
          if (playerCarId === null || socket?.readyState === WebSocket.OPEN || socket?.readyState === WebSocket.CONNECTING) {
            return;
          }
          let nextSocket;
          try {
            nextSocket = new WebSocket(bridgeUrl);
          } catch (error) {
            console.warn(`[PolyBot] Could not connect to ${bridgeUrl}`, error);
            scheduleReconnect();
            return;
          }
          socket = nextSocket;
          connectionGeneration += 1;
          const generation = connectionGeneration;
          nextSocket.addEventListener("open", () => {
            console.info(`[PolyBot] Connected to ${bridgeUrl}`);
          });
          nextSocket.addEventListener("message", (event) => {
            void onSocketMessage(nextSocket, generation, event.data);
          });
          nextSocket.addEventListener("close", () => {
            if (socket === nextSocket) {
              if (
                activeRequestToken?.sourceSocket === nextSocket &&
                activeRequestToken?.generation === generation
              ) {
                activeRequestToken = null;
              }
              socket = null;
              leaveManualMode();
              scheduleReconnect();
            }
          });
          nextSocket.addEventListener("error", () => {
            // The Python server is normally started after the race. The close
            // event schedules a quiet retry without interrupting the game.
          });
        }

        function observe(message) {
          const replayReply = message?.polybotVisualReplayReply;
          if (replayReply && Number.isSafeInteger(replayReply.id)) {
            const pending = visualReplayRequests.get(replayReply.id);
            if (pending) {
              clearTimeout(pending.timer);
              visualReplayRequests.delete(replayReply.id);
              if (replayReply.ok === true) pending.resolve(replayReply.result ?? {});
              else pending.reject(new BridgeError(
                "renderer_error",
                typeof replayReply.error === "string" ? replayReply.error : "main-thread replay command failed",
              ));
            }
            return;
          }
          if (internalDispatchDepth > 0) {
            return;
          }
          switch (message.messageType) {
            case messageTypes.Init:
              gameVersion = String(message.version ?? gameVersion);
              break;
            case messageTypes.CreateCar:
              createMessages.set(message.carId, message);
              startMessages.delete(message.carId);
              if (message.carRecording == null) {
                playerCarId = message.carId;
                try {
                  ghostRelay?.postMessage({
                    protocol: "polybot.ghost-relay",
                    v: 1,
                    source: workerRelayId,
                    op: "request",
                  });
                } catch (error) {
                  console.warn("[PolyBot] Could not request a reference ghost", error);
                }
                connectSocket();
              } else if (typeof message.trackData === "string") {
                localGhostMessages.set(message.trackData, message);
                relayGhost(message);
              }
              if (manualMode) {
                setTimeout(pauseManualCars, 0);
              }
              break;
            case messageTypes.DeleteCar: {
              const deletingPlayer = message.carId === playerCarId;
              createMessages.delete(message.carId);
              startMessages.delete(message.carId);
              if (deletingPlayer) {
                playerCarId = null;
                leaveManualMode();
                socket?.close(1000, "player left race");
              }
              break;
            }
            case messageTypes.StartCar:
              startMessages.set(message.carId, message);
              if (message.carId === playerCarId) {
                connectSocket();
              }
              if (manualMode) {
                setTimeout(pauseManualCars, 0);
              }
              break;
            default:
              break;
          }
        }

        return { observe };
      })();
    }

    self[runtimeKey].observe(r);
  }
}


class PolyBotBridgeMod extends PolyMod {
  touchingPhysics = true;

  preInit = (pml) => {
    if (typeof pml?.registerSimWorkerMixin !== "function") {
      throw new Error(
        "PolyBot Bridge requires PolyModLoader 0.6.2 with simulation-worker mixins.",
      );
    }

    const requestedPort = Number(new URL(location.href).searchParams.get("polybotPort") ?? 8765);
    const bridgePort = Number.isInteger(requestedPort) && requestedPort > 0 && requestedPort < 65536
      ? requestedPort : 8765;
    // Offline training workers are independent per port. Keep the native
    // one-instance guard within each port instead of blocking every simulator.
    pml.registerGlobalMixin({
      type: MixinType.REPLACEBETWEEN,
      tokenStart: '"polytrack-single-instance"',
      tokenEnd: '"polytrack-single-instance"',
      func: JSON.stringify("polytrack-single-instance-polybot-" + bridgePort),
    });
    globalThis.__polybotWrapSimulationWorker = (worker) => {
      const originalPostMessage = worker.postMessage.bind(worker);
      worker.postMessage = (message, ...options) => {
        const tagged = message && typeof message === "object" &&
          !ArrayBuffer.isView(message) && !(message instanceof ArrayBuffer)
          ? { ...message, polybotBridgePort: bridgePort } : message;
        return originalPostMessage(tagged, ...options);
      };
      let restartScheduled = false;
      const pressBackspace = () => {
        const eventOptions = {
          key: "Backspace", code: "Backspace", keyCode: 8, which: 8,
          bubbles: true, cancelable: true,
        };
        const keyboardTarget = document.body ?? document;
        keyboardTarget.dispatchEvent(new KeyboardEvent("keydown", eventOptions));
        keyboardTarget.dispatchEvent(new KeyboardEvent("keyup", eventOptions));
      };
      worker.addEventListener("message", (event) => {
        const command = event.data?.polybotVisualReplayCommand;
        if (command) {
          const reply = (message) => originalPostMessage({
            polybotVisualReplayReply: { id: command.id, ...message },
          });
          try {
            globalThis.__polybotVisualReplayDispatch(command, reply);
          } catch (error) {
            reply({ ok: false, error: error instanceof Error ? error.message : String(error) });
          }
        }
        const playerFinished = event.data?.polybotPlayerFinished === true;
        if (
          (event.data?.polybotAbortRestart !== true && !playerFinished) || restartScheduled
        ) return;
        restartScheduled = true;
        const restartDelayMs = playerFinished ? 500 : 0;
        setTimeout(() => { pressBackspace(); restartScheduled = false; }, restartDelayMs);
      });
      return worker;
    };
    const replayState = {
      context: null,
      ghosts: [],
      loading: null,
      playbackSeconds: 0,
      playing: false,
      speed: 1,
      opacity: 0.5,
      endBehavior: "fade",
      fadeDuration: 0.75,
      renderFrames: 0,
      renderTimeMs: 0,
    };
    const replayMaxGhosts = 500;
    const replayMaxSamplesPerGhost = 500000;
    const replayMaxTotalSamples = 250000;
    const replayMaxPayloadBytes = 33554432;
    const replayPendingCommands = [];
    const replayFinite = (value, label) => {
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new Error(`${label} must be finite`);
      }
      return value;
    };
    const replayColor = (value) => {
      if (typeof value !== "string" || !/^#[0-9a-fA-F]{6}$/.test(value)) {
        throw new Error("color must be #RRGGBB");
      }
      return value.toLowerCase();
    };
    const replayClear = () => {
      replayState.playing = false;
      const loading = replayState.loading;
      replayState.loading = null;
      for (const ghost of replayState.ghosts) {
        if (ghost.car) ghost.car.dispose();
        ghost.car = null;
        ghost.samples = null;
      }
      if (loading) {
        for (const episode of loading.episodes.values()) {
          if (episode.car) episode.car.dispose();
          episode.car = null;
          episode.samples = null;
        }
      }
      replayState.ghosts.length = 0;
      replayState.playbackSeconds = 0;
      replayState.renderFrames = 0;
      replayState.renderTimeMs = 0;
    };
    const replayValidateSample = (sample, previous) => {
      if (!Array.isArray(sample) || sample.length !== 9) {
        throw new Error("each replay sample must contain tick, elapsed_s, position, and quaternion");
      }
      if (!sample.every((value) => typeof value === "number" && Number.isFinite(value))) {
        throw new Error("replay sample values must be finite numbers");
      }
      if (!Number.isSafeInteger(sample[0]) || sample[0] < 0 || sample[1] < 0) {
        throw new Error("replay sample tick and elapsed_s must be non-negative");
      }
      const quaternionNorm = Math.hypot(sample[5], sample[6], sample[7], sample[8]);
      if (quaternionNorm < 1e-6) throw new Error("replay quaternion cannot be zero");
      for (let index = 5; index < 9; index += 1) sample[index] /= quaternionNorm;
      if (previous && (sample[0] < previous[0] || sample[1] < previous[1])) {
        throw new Error("replay samples must be ordered by tick and elapsed_s");
      }
      return sample;
    };
    const replayResetIndex = (ghost, target) => {
      const samples = ghost.samples;
      let low = 1;
      let high = samples.length - 1;
      while (low < high) {
        const middle = (low + high) >>> 1;
        if (samples[middle][1] < target) low = middle + 1;
        else high = middle;
      }
      ghost.sampleIndex = low;
    };
    const replaySetGhostColor = (ghost) => {
      const style = replayState.context.player.getCarStyle().clone();
      style.primaryHex = Number.parseInt(ghost.color.slice(1), 16);
      ghost.car.setCarStyle(style);
    };
    const replayCreateGhostCar = (ghost) => {
      const base = replayState.context.player.getCarState();
      ghost.car = replayState.context.createCar(base);
      ghost.renderState = {
        ...base,
        frames: 0,
        hasStarted: true,
        finishFrames: null,
        position: ghost.position,
        quaternion: ghost.orientation,
        controls: { up: false, right: false, down: false, left: false, reset: false },
      };
      ghost.car.audioVolume = 0;
      ghost.car.isPaused = true;
      replaySetGhostColor(ghost);
      ghost.car.setOpacity(replayState.opacity);
      ghost.car.setVisible(false);
    };
    const replayBeginSwarm = (params) => {
      if (!Number.isSafeInteger(params.ghost_count) || params.ghost_count < 1 ||
          params.ghost_count > replayMaxGhosts) {
        throw new Error(`ghost_count must be from 1 to ${replayMaxGhosts}`);
      }
      if (!Number.isSafeInteger(params.total_sample_count) || params.total_sample_count < 1 ||
          params.total_sample_count > replayMaxTotalSamples) {
        throw new Error(`total_sample_count must be from 1 to ${replayMaxTotalSamples}`);
      }
      if (!Number.isSafeInteger(params.payload_bytes) || params.payload_bytes < 1 ||
          params.payload_bytes > replayMaxPayloadBytes) {
        throw new Error(`payload_bytes must be from 1 to ${replayMaxPayloadBytes}`);
      }
      if (!["disappear", "freeze", "fade"].includes(params.end_behavior)) {
        throw new Error("invalid end_behavior");
      }
      const speed = replayFinite(params.speed, "speed");
      const opacity = replayFinite(params.opacity, "opacity");
      const fadeDuration = replayFinite(params.fade_duration_s, "fade_duration_s");
      if (speed < 0.1 || speed > 8) throw new Error("speed must be from 0.1 to 8");
      if (opacity < 0 || opacity > 1) throw new Error("opacity must be from 0 to 1");
      if (fadeDuration < 0 || fadeDuration > 10) {
        throw new Error("fade_duration_s must be from 0 to 10");
      }
      replayClear();
      replayState.speed = speed;
      replayState.opacity = opacity;
      replayState.endBehavior = params.end_behavior;
      replayState.fadeDuration = fadeDuration;
      replayState.loading = {
        expectedGhosts: params.ghost_count,
        expectedSamples: params.total_sample_count,
        expectedBytes: params.payload_bytes,
        declaredSamples: 0,
        receivedSamples: 0,
        receivedBytes: 0,
        episodes: new Map(),
        openEpisode: null,
      };
      return { accepted: true, ghost_count: params.ghost_count };
    };
    const replayBeginEpisode = (params) => {
      const loading = replayState.loading;
      if (!loading || loading.openEpisode) throw new Error("no swarm is accepting an episode");
      if (typeof params.episode_id !== "string" || !params.episode_id ||
          params.episode_id.length > 128 || loading.episodes.has(params.episode_id)) {
        throw new Error("episode_id must be unique non-empty text of at most 128 characters");
      }
      if (!Number.isSafeInteger(params.training_step_start) || params.training_step_start < 0) {
        throw new Error("training_step_start must be a non-negative safe integer");
      }
      if (!Number.isSafeInteger(params.sample_count) || params.sample_count < 1 ||
          params.sample_count > replayMaxSamplesPerGhost) {
        throw new Error(`sample_count must be from 1 to ${replayMaxSamplesPerGhost}`);
      }
      if (loading.declaredSamples + params.sample_count > loading.expectedSamples) {
        throw new Error("episode declarations exceed total_sample_count");
      }
      const episode = {
        episodeId: params.episode_id,
        trainingStepStart: params.training_step_start,
        color: replayColor(params.color),
        expected: params.sample_count,
        samples: [],
        sampleIndex: 1,
        duration: 0,
        car: null,
        position: { x: 0, y: 0, z: 0 },
        orientation: { x: 0, y: 0, z: 0, w: 1 },
        lastOpacity: null,
        visible: false,
      };
      loading.episodes.set(episode.episodeId, episode);
      loading.openEpisode = episode;
      loading.declaredSamples += episode.expected;
      return { accepted: true, episode_id: episode.episodeId };
    };
    const replayAddChunk = (params) => {
      const loading = replayState.loading;
      const episode = loading && loading.openEpisode;
      if (!episode || (params.episode_id !== undefined && params.episode_id !== episode.episodeId) ||
          !Array.isArray(params.samples) || params.samples.length < 1 ||
          params.samples.length > 256 || params.start !== episode.samples.length) {
        throw new Error("invalid or out-of-order swarm replay chunk");
      }
      if (episode.samples.length + params.samples.length > episode.expected) {
        throw new Error("replay chunk exceeds declared sample_count");
      }
      const bytes = new TextEncoder().encode(JSON.stringify(params.samples)).length;
      if (loading.receivedBytes + bytes > loading.expectedBytes ||
          loading.receivedBytes + bytes > replayMaxPayloadBytes) {
        throw new Error("swarm chunks exceed declared payload_bytes");
      }
      const checked = [];
      let previous = episode.samples.at(-1);
      for (const sample of params.samples) {
        checked.push(replayValidateSample(sample, previous));
        previous = sample;
      }
      loading.receivedBytes += bytes;
      episode.samples.push(...checked);
      loading.receivedSamples += checked.length;
      return { episode_id: episode.episodeId, received: episode.samples.length };
    };
    const replayCommitEpisode = (params = {}) => {
      const loading = replayState.loading;
      const episode = loading && loading.openEpisode;
      if (!episode || (params.episode_id !== undefined && params.episode_id !== episode.episodeId) ||
          episode.samples.length !== episode.expected) {
        throw new Error("episode payload is incomplete");
      }
      episode.duration = episode.samples.at(-1)[1] - episode.samples[0][1];
      if (replayState.context) replayCreateGhostCar(episode);
      loading.openEpisode = null;
      return { episode_id: episode.episodeId, committed: true };
    };
    const replayCommitSwarm = (params) => {
      const loading = replayState.loading;
      if (!loading || loading.openEpisode || loading.episodes.size !== loading.expectedGhosts ||
          loading.declaredSamples !== loading.expectedSamples ||
          loading.receivedSamples !== loading.expectedSamples ||
          loading.receivedBytes > loading.expectedBytes) {
        throw new Error("swarm payload is incomplete");
      }
      try {
        for (const episode of loading.episodes.values()) {
          if (!episode.car) replayCreateGhostCar(episode);
          replayState.ghosts.push(episode);
        }
      } catch (error) {
        replayClear();
        throw error;
      }
      replayState.loading = null;
      replayState.playbackSeconds = 0;
      replayState.playing = params.autoplay === true;
      replayRender(0);
      return replayStatus();
    };
    const replayStatus = () => {
      let visible = 0;
      let minimumStep = null;
      let maximumStep = null;
      let duration = 0;
      for (const ghost of replayState.ghosts) {
        if (ghost.visible) visible += 1;
        minimumStep = minimumStep === null
          ? ghost.trainingStepStart : Math.min(minimumStep, ghost.trainingStepStart);
        maximumStep = maximumStep === null
          ? ghost.trainingStepStart : Math.max(maximumStep, ghost.trainingStepStart);
        duration = Math.max(duration, ghost.duration);
      }
      return {
        loaded_ghosts: replayState.ghosts.length,
        visible_ghosts: visible,
        playing: replayState.playing,
        playback_seconds: replayState.playbackSeconds,
        duration_seconds: duration,
        training_step_range: minimumStep === null ? null : [minimumStep, maximumStep],
        average_render_ms: replayState.renderFrames
          ? replayState.renderTimeMs / replayState.renderFrames : 0,
      };
    };
    const replaySlerpInto = (left, right, fraction, result) => {
      let ax = left[5], ay = left[6], az = left[7], aw = left[8];
      let bx = right[5], by = right[6], bz = right[7], bw = right[8];
      let dot = ax * bx + ay * by + az * bz + aw * bw;
      if (dot < 0) {
        dot = -dot;
        bx = -bx; by = -by; bz = -bz; bw = -bw;
      }
      let leftWeight;
      let rightWeight;
      if (dot > 0.9995) {
        leftWeight = 1 - fraction;
        rightWeight = fraction;
      } else {
        const angle = Math.acos(Math.max(-1, Math.min(1, dot)));
        const inverseSin = 1 / Math.sin(angle);
        leftWeight = Math.sin((1 - fraction) * angle) * inverseSin;
        rightWeight = Math.sin(fraction * angle) * inverseSin;
      }
      let x = leftWeight * ax + rightWeight * bx;
      let y = leftWeight * ay + rightWeight * by;
      let z = leftWeight * az + rightWeight * bz;
      let w = leftWeight * aw + rightWeight * bw;
      const norm = 1 / Math.hypot(x, y, z, w);
      result.x = x * norm; result.y = y * norm; result.z = z * norm; result.w = w * norm;
    };
    const replayInterpolateInto = (ghost, elapsed, output) => {
      const samples = ghost.samples;
      const lastIndex = samples.length - 1;
      const first = samples[0];
      if (lastIndex === 0) {
        output.source = first;
        output.fraction = 0;
        output.left = first;
        output.right = first;
        return output;
      }
      const target = first[1] + elapsed;
      while (ghost.sampleIndex < lastIndex && samples[ghost.sampleIndex][1] < target) {
        ghost.sampleIndex += 1;
      }
      if (target <= first[1]) {
        output.source = first;
        output.fraction = 0;
        output.left = first;
        output.right = first;
        return output;
      }
      const right = samples[ghost.sampleIndex];
      const left = samples[ghost.sampleIndex - 1];
      const span = right[1] - left[1];
      output.left = left;
      output.right = right;
      output.fraction = span > 0 ? Math.max(0, Math.min(1, (target - left[1]) / span)) : 1;
      output.source = null;
      return output;
    };
    const replayRender = (deltaSeconds) => {
      if (!replayState.ghosts.length) return;
      const frameStart = performance.now();
      if (replayState.playing && Number.isFinite(deltaSeconds) && deltaSeconds > 0) {
        replayState.playbackSeconds += deltaSeconds * replayState.speed;
      }
      const interval = { source: null, left: null, right: null, fraction: 0 };
      for (const ghost of replayState.ghosts) {
        const elapsed = replayState.playbackSeconds;
        const ended = elapsed > ghost.duration;
        if (ended && replayState.endBehavior === "disappear") {
          if (ghost.visible) ghost.car.setVisible(false);
          ghost.visible = false;
          continue;
        }
        let opacity = replayState.opacity;
        if (ended && replayState.endBehavior === "fade") {
          opacity *= replayState.fadeDuration > 0
            ? Math.max(0, 1 - (elapsed - ghost.duration) / replayState.fadeDuration)
            : 0;
          if (opacity <= 0) {
            if (ghost.visible) ghost.car.setVisible(false);
            ghost.visible = false;
            continue;
          }
        }
        const localElapsed = ended ? ghost.duration : elapsed;
        replayInterpolateInto(ghost, localElapsed, interval);
        const left = interval.left;
        const right = interval.right;
        const fraction = interval.fraction;
        const source = interval.source;
        const orientation = ghost.orientation;
        const positionX = source ? source[2] : left[2] + fraction * (right[2] - left[2]);
        const positionY = source ? source[3] : left[3] + fraction * (right[3] - left[3]);
        const positionZ = source ? source[4] : left[4] + fraction * (right[4] - left[4]);
        if (source) {
          orientation.x = source[5]; orientation.y = source[6];
          orientation.z = source[7]; orientation.w = source[8];
        } else {
          replaySlerpInto(left, right, fraction, orientation);
        }
        if (!ghost.visible) ghost.car.setVisible(true);
        ghost.visible = true;
        if (ghost.lastOpacity !== opacity) {
          ghost.car.setOpacity(opacity);
          ghost.lastOpacity = opacity;
        }
        const elapsedAtTransform = source ? source[1] : left[1] + fraction * (right[1] - left[1]);
        ghost.position.x = positionX;
        ghost.position.y = positionY;
        ghost.position.z = positionZ;
        const state = ghost.renderState;
        state.frames = Math.round(elapsedAtTransform * 1000);
        state.position = ghost.position;
        state.quaternion = orientation;
        ghost.car.setCarState(state, false);
        ghost.car.isPaused = true;
        ghost.car.audioVolume = 0;
        ghost.car.update(deltaSeconds);
      }
      replayState.renderFrames += 1;
      replayState.renderTimeMs += performance.now() - frameStart;
    };
    const replayDispatch = (command) => {
      if (!command || typeof command.op !== "string" || !command.params ||
          typeof command.params !== "object" || Array.isArray(command.params)) {
        throw new Error("malformed visual replay command");
      }
      const params = command.params;
      switch (command.op) {
        case "begin": {
          const color = replayColor(params.color);
          replayBeginSwarm({
            ghost_count: 1,
            total_sample_count: params.sample_count,
            payload_bytes: params.payload_bytes ?? replayMaxPayloadBytes,
            speed: params.speed,
            opacity: params.opacity,
            end_behavior: params.end_behavior,
            fade_duration_s: params.fade_duration_s,
          });
          replayBeginEpisode({
            episode_id: "legacy",
            training_step_start: 0,
            sample_count: params.sample_count,
            color,
          });
          return { accepted: true, sample_count: params.sample_count };
        }
        case "chunk": {
          return replayAddChunk(params);
        }
        case "commit": {
          replayCommitEpisode();
          return replayCommitSwarm(params);
        }
        case "swarm_begin":
          return replayBeginSwarm(params);
        case "swarm_episode_begin":
          return replayBeginEpisode(params);
        case "swarm_chunk":
          return replayAddChunk(params);
        case "swarm_episode_commit":
          return replayCommitEpisode(params);
        case "swarm_commit":
          return replayCommitSwarm(params);
        case "play":
          if (!replayState.ghosts.length) throw new Error("no visual replay swarm is loaded");
          replayState.playing = true;
          return replayStatus();
        case "pause":
          replayState.playing = false;
          return replayStatus();
        case "restart":
          if (!replayState.ghosts.length) throw new Error("no visual replay swarm is loaded");
          replayState.playbackSeconds = 0;
          for (const ghost of replayState.ghosts) replayResetIndex(ghost, ghost.samples[0][1]);
          replayState.playing = true;
          replayRender(0);
          return replayStatus();
        case "seek": {
          if (!replayState.ghosts.length) throw new Error("no visual replay swarm is loaded");
          const seconds = replayFinite(params.seconds, "seconds");
          const duration = Math.max(...replayState.ghosts.map((ghost) => ghost.duration));
          if (seconds < 0 || seconds > duration) throw new Error(`seek seconds must be from 0 to ${duration}`);
          replayState.playbackSeconds = seconds;
          for (const ghost of replayState.ghosts) {
            replayResetIndex(ghost, ghost.samples[0][1] + Math.min(seconds, ghost.duration));
          }
          replayRender(0);
          return replayStatus();
        }
        case "speed": {
          const speed = replayFinite(params.value, "speed");
          if (speed < 0.1 || speed > 8) throw new Error("speed must be from 0.1 to 8");
          replayState.speed = speed;
          return replayStatus();
        }
        case "opacity": {
          const opacity = replayFinite(params.value, "opacity");
          if (opacity < 0 || opacity > 1) throw new Error("opacity must be from 0 to 1");
          replayState.opacity = opacity;
          for (const ghost of replayState.ghosts) {
            ghost.car.setOpacity(opacity);
            ghost.lastOpacity = opacity;
          }
          replayRender(0);
          return replayStatus();
        }
        case "color": {
          const color = replayColor(params.value);
          for (const ghost of replayState.ghosts) {
            ghost.color = color;
            replaySetGhostColor(ghost);
          }
          return replayStatus();
        }
        case "end_behavior":
          if (!["disappear", "freeze", "fade"].includes(params.value)) {
            throw new Error("invalid end_behavior");
          }
          replayState.endBehavior = params.value;
          replayRender(0);
          return replayStatus();
        case "fade_duration": {
          const duration = replayFinite(params.value, "fade_duration_s");
          if (duration < 0 || duration > 10) throw new Error("fade_duration_s must be from 0 to 10");
          replayState.fadeDuration = duration;
          replayRender(0);
          return replayStatus();
        }
        case "clear":
          replayClear();
          return replayStatus();
        case "status":
          return replayStatus();
        default:
          throw new Error(`unsupported visual replay command: ${command.op}`);
      }
    };
    globalThis.__polybotVisualReplayDispatch = (command, reply) => {
      if (!replayState.context && ![
        "begin", "chunk", "swarm_begin", "swarm_episode_begin", "swarm_chunk",
        "swarm_episode_commit",
      ].includes(command.op)) {
        replayPendingCommands.push({ command, reply });
        return;
      }
      try {
        reply({ ok: true, result: replayDispatch(command) });
      } catch (error) {
        reply({ ok: false, error: error instanceof Error ? error.message : String(error) });
      }
    };
    globalThis.__polybotBindVisualReplayRenderer = (context) => {
      if (replayState.context && replayState.context.owner !== context.owner) replayClear();
      replayState.context = context;
      while (replayPendingCommands.length) {
        const { command, reply } = replayPendingCommands.shift();
        try {
          reply({ ok: true, result: replayDispatch(command) });
        } catch (error) {
          reply({ ok: false, error: error instanceof Error ? error.message : String(error) });
        }
      }
      replayRender(context.deltaSeconds);
    };

    pml.registerSimWorkerMixin({
      type: MixinType.INSERT,
      token: "const r = i.data;",
      func: polybotWorkerInjection,
    });
    pml.registerGlobalMixin({
      type: MixinType.REPLACEBETWEEN,
      tokenStart: "new Worker(ActivePolyModLoader.getSimURL())",
      tokenEnd: "new Worker(ActivePolyModLoader.getSimURL())",
      func: "globalThis.__polybotWrapSimulationWorker(new Worker(ActivePolyModLoader.getSimURL()))",
    });
    pml.registerGlobalMixin({
      type: MixinType.REPLACEBETWEEN,
      tokenStart: "this.setCarState(e, !1);",
      tokenEnd: "this.setCarState(e, !1);",
      // The worker recreates cars on reset. Clear the local player's recorder
      // and prime its previous state before recording the first new tick.
      // The native recorder uses the PREVIOUS state's frame and finish flag.
      func: `{
        const previous = this.getCarState();
        const rewind = e.frames <= previous.frames;
        if (rewind && (0, l.gn)(this, ie, "f")) {
          (0, l.GG)(this, re, new st.A(), "f");
          (0, l.GG)(this, te, {
            ...previous,
            frames: Math.max(0, e.frames - 1),
            finishFrames: null,
            nextCheckpointIndex: 0,
            controls: { up: false, right: false, down: false, left: false, reset: false },
          }, "f");
        }
        this.setCarState(e, rewind);
      }`,
    });
    pml.registerGlobalMixin({
      type: MixinType.INSERT,
      token: 'update(e) {\n              const t = (0, R.gn)(this, ta, "m", Ps).call(this);',
      func: `globalThis.__polybotBindVisualReplayRenderer({
        owner: this,
        deltaSeconds: e,
        player: (0, R.gn)(this, Xa, "f"),
        createCar: (state) => new z.A(
          null, state, null, null,
          (0, R.gn)(this, la, "f"),
          (0, R.gn)(this, ca, "f"),
          (0, R.gn)(this, aa, "f"),
          (0, R.gn)(this, ra, "f"),
          (0, R.gn)(this, Ta, "f"),
          (0, R.gn)(this, ua, "f"),
          null,
        ),
      });`,
    });
    for (const token of [
      "submitLeaderboard(e, t, n, i, r, a, s, o) {",
      "submitUserProfile(e, t, n, i) {",
      "verifyRecordings(e, t, n, i, r) {",
      "getIceServers() {",
    ]) {
      pml.registerGlobalMixin({
        type: MixinType.INSERT, token,
        func: 'return Promise.reject(new Error("PolyBot offline mode"));',
      });
    }
    for (const token of [
      "createMultiplayerHostWebSocket() {", "createMultiplayerJoinWebSocket() {",
    ]) {
      pml.registerGlobalMixin({
        type: MixinType.INSERT, token,
        func: 'throw new Error("PolyBot offline mode");',
      });
    }
  };
}

export const polyMod = new PolyBotBridgeMod();
