"""Bundle the latest bridge worker into the PML entry point.

PML can import cached entry points from blob URLs, so relative imports fail.
Bundling also prevents a new release from loading an older pinned runtime.
"""

from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    root = Path(__file__).resolve().parents[1] / "pml-mod"
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    for version in dict.fromkeys(manifest["latest"].values()):
        directory = root / version
        template = (directory / "main.template.js").read_text(encoding="utf-8")
        runtime = (directory / "worker_runtime.js").read_text(encoding="utf-8")
        if template.count("/* POLYBOT_WORKER_RUNTIME */") != 1:
            raise ValueError("Expected exactly one worker runtime placeholder")
        source = template.replace(
            "/* POLYBOT_WORKER_RUNTIME */",
            runtime.replace("export function polybotWorkerInjection()", "function polybotWorkerInjection()", 1),
        )
        renderer_placeholder = "/* POLYBOT_HUD_RENDERER */"
        if renderer_placeholder in source:
            renderer_path = directory / "hud_renderer.mjs"
            renderer = renderer_path.read_text(encoding="utf-8")
            renderer_export = "export function installPolyBotHudOverlay("
            if renderer.count(renderer_export) != 1:
                raise ValueError(f"Expected one HUD renderer export in {renderer_path}")
            source = source.replace(
                renderer_placeholder,
                renderer.replace(renderer_export, "function installPolyBotHudOverlay(", 1),
            )
        (directory / "main.mod.js").write_text(
            "// Generated by tools/build_pml_mod.py; edit main.template.js and worker_runtime.js.\n" + source,
            encoding="utf-8", newline="\n",
        )
        print(f"Bundled bridge {version}")


if __name__ == "__main__":
    main()
